version: '3'
services: 
  malgarweb:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
      - /Users/mauricio.garcia/Documents/Personal-Projects/Docker/frontend/:/app
  tests: 
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - /Users/mauricio.garcia/Documents/Personal-Projects/Docker/frontend/:/app
    command: ["npm", "run", "test"]    
